ASP_PRUEBA/ASP_PRUEBA/Models/ErrorViewModel.cs
namespace ASP_PRUEBA.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP_PRUEBA/ASP_PRUEBA/Models/Persona.cs
namespace ASP_PRUEBA.Models
{
    public class Persona
    {
        public int peId { get; set; }

        public string? peNombres { get; set; }

        public string? peApellidos { get; set; }

        public string? peIdentificacion { get; set; }

        public string? peEmail { get; set; }

        public string? peTipoIdentificacion { get; set; }

        public DateTime peFechaCreacion { get; set; }

        public string? peCodigoPersona { get; set; }

        public string? peNombreCompleto { get; set; }
    }
}

ASP_PRUEBA/ASP_PRUEBA/Models/ResultadoAPI.cs
namespace ASP_PRUEBA.Models
{
    public class ResultadoAPI
    {
        public string mensaje { get; set; }

        public List<Persona>? lista { get; set; }

        public Persona? persona { get; set; }
    }
}

ASP_PRUEBA/ASP_PRUEBA/Models/ResultadoCredential.cs
namespace ASP_PRUEBA.Models
{
    public class ResultadoCredential
    {
        public string token { get; set; }
    }
}

ASP_PRUEBA/ASP_PRUEBA/Models/Usuario.cs
namespace ASP_PRUEBA.Models
{
    public class Usuario
    {
        public string? usUsuario { get; set; }

        public string? usPassword { get; set; }
    }
}

ASP_PRUEBA/ASP_PRUEBA/Controllers/AutenticationController.cs
using ASP_PRUEBA.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ASP_PRUEBA.Servicios;

namespace ASP_PRUEBA.Controllers
{
    public class AutenticationController : Controller
    {
        private readonly IServicioAPI _servicioAPI;

        public AutenticationController(IServicioAPI servicioAPI)
        {
            _servicioAPI = servicioAPI;
        }

        public async Task<IActionResult> Login()
        {
            Usuario usuario = new Usuario();

            await _servicioAPI.Salir();

            return View(usuario);
        }

        [HttpPost]
        public async Task<IActionResult> Validar(Usuario usuario)
        {
            bool respuesta = false;

            respuesta = await _servicioAPI.Validar(usuario);

            if (respuesta)
                return RedirectToAction("Index", "Home");
            else
                return NoContent();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP_PRUEBA/ASP_PRUEBA/Controllers/HomeController.cs
using ASP_PRUEBA.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ASP_PRUEBA.Servicios;

namespace ASP_PRUEBA.Controllers
{
    public class HomeController : Controller
    {
        private readonly IServicioAPI _servicioAPI;

        public HomeController(IServicioAPI servicioAPI)
        {
            _servicioAPI = servicioAPI;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<Persona> lista = await _servicioAPI.Lista();

            return View(lista);
        }

        public async Task<IActionResult> Persona()
        {
            Persona persona = new Persona();

            return View(persona);
        }

        [HttpPost]
        public async Task<IActionResult> Guardar(Persona persona)
        {
            bool respuesta = false;

            if(persona.peId == 0)
            {
                respuesta = await _servicioAPI.Guardar(persona);
            }

            if (respuesta)
                return RedirectToAction("Index");
            else
                return NoContent();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP_PRUEBA/ASP_PRUEBA/Views/Autentication/Login.cshtml
@model Usuario
@{
    ViewData["Title"] = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
	<div class="user_card">
		<h1>Login</h1>
	</div>
	<div class="card_body">
		<form asp-action="Validar" asp-controller="Autentication" method="post">

			<div class="mb-2">
				<label class="form-label">Usuario</label>
				<input type="text" class="form-control form-control-sm" asp-for="usUsuario" placeholder="****">
			</div>

			<div class="mb-2">
				<label class="form-label">Contraseña</label>
				<input type="password" class="form-control form-control-sm" asp-for="usPassword" placeholder="****">
			</div>
				 		
			<button type="submit" class="btn btn-success btn-sm">Ingresar</button>

		</form>
	</div>
</div>

ASP_PRUEBA/ASP_PRUEBA/Views/Home/Index.cshtml
@model List<Persona>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    
</div>

<div class="card">
    <div class="card-header">
        Lista de Personas
    </div>
    <div class="card-body">
        <a asp-action="Persona" asp-controller="Home" class="btn btn-success btn-sm">Nueva Persona</a>
        <hr/>

        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>NOMBRES</th>
                    <th>APELLIDOS</th>
                    <th>IDENFITICACION</th>
                    <th>EMAIL</th>
                    <th>TIPO IDENTIFICACIÓN</th>
                    <th>FECHA CREACION</th>
                    <th>CODIGO PERSONA</th>
                    <th>NOMBRE COMPLETO</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model){
                    <tr>
                        <td>@item.peId</td>
                        <td>@item.peNombres</td>
                        <td>@item.peApellidos</td>
                        <td>@item.peIdentificacion</td>
                        <td>@item.peEmail</td>
                        <td>@item.peTipoIdentificacion</td>
                        <td>@Convert.ToDateTime(@item.peFechaCreacion).ToString("yyyy-MM-dd")</td>
                        <td>@item.peCodigoPersona</td>
                        <td>@item.peNombreCompleto</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

ASP_PRUEBA/ASP_PRUEBA/Views/Home/Persona.cshtml
@model Persona
@{
    ViewData["Title"] = "Persona";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Nueva Persona
    </div>
    <div class="card-body">
        <form asp-action="Guardar" asp-controller="Home" method="post">
            <input asp-for="peId" type="hidden"/>

            <div class="mb-2">
                <label class="form-label">Nombres</label>
                <input type="text" class="form-control form-control-sm" asp-for="peNombres"/>
            </div>
            <div class="mb-2">
                <label class="form-label">Apellidos</label>
                <input type="text" class="form-control form-control-sm" asp-for="peApellidos" />
            </div>
            <div class="mb-2">
                <label class="form-label">Identificacion</label>
                <input type="text" class="form-control form-control-sm" asp-for="peIdentificacion" />
            </div>
            <div class="mb-2">
                <label class="form-label">Email</label>
                <input type="text" class="form-control form-control-sm" asp-for="peEmail"/>
            </div>
            <div class="mb-2">
                <label class="form-label">Tipo Identificación</label>
                <input type="text" class="form-control form-control-sm" asp-for="peTipoIdentificacion" />
            </div>
            <div class="mb-2">
                <label class="form-label">Fecha Creación</label>
                <input type="date" class="form-control form-control-sm" asp-for="peFechaCreacion" />
            </div>

            <button type="submit" class="btn btn-success btn-sm">Guardar</button>

            <a asp-action="Index" asp-controller="Home" class="btn btn-warning btn-sm">Cancelar</a>
        </form>
        <hr/>
    </div>
</div>

ASP_PRUEBA/ASP_PRUEBA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP_PRUEBA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP_PRUEBA.styles.css" asp-append-version="true" />
    <title>My Awesome Login Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP_PRUEBA</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Autentication" asp-action="Login">Salir</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ASP_PRUEBA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>